### ISSUE TITLE
请问一下为何ImportError: No module named detectors.detector_factory

### ISSUE THREAD

**Issue by jhgfkdj** [chenjun2hao/CenterFace.pytorch#17]
直接进入src中执行python test_wider_face.py就报这个错误。

当然我后来改了用sys.path.append('lib/detectors'), sys.path.append('lib/datasets'), 
然后from detector_factory import detector_factory
这样就在这一步导入没问题。

但是后面detector_factory.py中的带前点的import全都要去掉点，以及要from external.nms import xx的时候又出问题。搞不清这个路径到底该如何导入了，感觉有点复杂。

**Comment by chenjun2hao** [comment]
nms需要编译一下，参考centernet。
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jhgfkdj"<notifications@github.com&gt;; 
发送时间: 2020年4月26日(星期天) 晚上6:12
收件人: "chenjun2hao/CenterFace.pytorch"<CenterFace.pytorch@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [chenjun2hao/CenterFace.pytorch] 请问一下为何ImportError: No module named detectors.detector_factory (#17)





 
直接进入src中执行python test_wider_face.py就报这个错误。
 
当然我后来改了用sys.path.append('lib/detectors'), sys.path.append('lib/datasets'),
 然后from detector_factory import detector_factory
 这样就在这一步导入没问题。
 
但是后面detector_factory.py中的带前点的import全都要去掉点，以及要from external.nms import xx的时候又出问题。搞不清这个路径到底该如何导入了，感觉有点复杂。

**Comment by jhgfkdj** [comment]
> nms需要编译一下，参考centernet。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jhgfkdj"<notifications@github.com&gt;; 发送时间: 2020年4月26日(星期天) 晚上6:12 收件人: "chenjun2hao/CenterFace.pytorch"<CenterFace.pytorch@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [chenjun2hao/CenterFace.pytorch] 请问一下为何ImportError: No module named detectors.detector_factory (#17) 直接进入src中执行python test_wider_face.py就报这个错误。 当然我后来改了用sys.path.append('lib/detectors'), sys.path.append('lib/datasets'), 然后from detector_factory import detector_factory 这样就在这一步导入没问题。 但是后面detector_factory.py中的带前点的import全都要去掉点，以及要from external.nms import xx的时候又出问题。搞不清这个路径到底该如何导入了，感觉有点复杂。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你指的是单独nms需要编译，还是lib中的其他东西也需要编译？因为你看我之前说的，还没到nms那一步， 就无法使用form 文件夹.文件 import 函数这个方法

**Comment by chenjun2hao** [comment]
nms编译之后才能。同时参考要求的python版本。
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jhgfkdj"<notifications@github.com&gt;; 
发送时间: 2020年4月26日(星期天) 晚上6:16
收件人: "chenjun2hao/CenterFace.pytorch"<CenterFace.pytorch@noreply.github.com&gt;; 
抄送: "陈军"<778961303@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [chenjun2hao/CenterFace.pytorch] 请问一下为何ImportError: No module named detectors.detector_factory (#17)





  
nms需要编译一下，参考centernet。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jhgfkdj"<notifications@github.com&gt;; 发送时间: 2020年4月26日(星期天) 晚上6:12 收件人: "chenjun2hao/CenterFace.pytorch"<CenterFace.pytorch@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [chenjun2hao/CenterFace.pytorch] 请问一下为何ImportError: No module named detectors.detector_factory (#17) 直接进入src中执行python test_wider_face.py就报这个错误。 当然我后来改了用sys.path.append('lib/detectors'), sys.path.append('lib/datasets'), 然后from detector_factory import detector_factory 这样就在这一步导入没问题。 但是后面detector_factory.py中的带前点的import全都要去掉点，以及要from external.nms import xx的时候又出问题。搞不清这个路径到底该如何导入了，感觉有点复杂。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你指的是单独nms需要编译，还是lib中的其他东西也需要编译？因为你看我之前说的，还没到nms那一步， 就无法使用form 文件夹.文件 import 函数这个方法

**Comment by jhgfkdj** [comment]
> nms编译之后才能。同时参考要求的python版本。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jhgfkdj"<notifications@github.com&gt;; 发送时间: 2020年4月26日(星期天) 晚上6:16 收件人: "chenjun2hao/CenterFace.pytorch"<CenterFace.pytorch@noreply.github.com&gt;; 抄送: "陈军"<778961303@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [chenjun2hao/CenterFace.pytorch] 请问一下为何ImportError: No module named detectors.detector_factory (#17) nms需要编译一下，参考centernet。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jhgfkdj"<notifications@github.com&gt;; 发送时间: 2020年4月26日(星期天) 晚上6:12 收件人: "chenjun2hao/CenterFace.pytorch"<CenterFace.pytorch@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [chenjun2hao/CenterFace.pytorch] 请问一下为何ImportError: No module named detectors.detector_factory (#17) 直接进入src中执行python test_wider_face.py就报这个错误。 当然我后来改了用sys.path.append('lib/detectors'), sys.path.append('lib/datasets'), 然后from detector_factory import detector_factory 这样就在这一步导入没问题。 但是后面detector_factory.py中的带前点的import全都要去掉点，以及要from external.nms import xx的时候又出问题。搞不清这个路径到底该如何导入了，感觉有点复杂。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 你指的是单独nms需要编译，还是lib中的其他东西也需要编译？因为你看我之前说的，还没到nms那一步， 就无法使用form 文件夹.文件 import 函数这个方法 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

原来如此，是python版本的问题，我用的2。 多谢解答

**Comment by QAQEthan** [comment]
我也遇到了，请问怎么解决
